version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: docker-dev/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx:stable-alpine
    working_dir: /var/www/html
    ports:
      - "57201:80"
    volumes:
      - ./:/var/www/html
      - ./docker-dev/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=myApp
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myApp
      - MYSQL_PASSWORD=myApp
  adminer:
    image: adminer
    ports:
      - "57203:8080"
networks:
  default:
    driver: bridge
